services:
  mysql:
      image: mysql:8.0
      container_name: mysql
      restart: unless-stopped
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: innyx
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - mysql_data:/var/lib/mysql

  laravel-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    networks:
      - innyx
    ports:
      - 8000:80

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - innyx
    depends_on:
      - laravel-app

networks:
  innyx:
    driver: bridge

volumes:
  mysql_data:
